// This Arduino sketch was automatically generated by IrScrutinizer 2.3.0 using Bomaker Ondine 1 Soundbar.rmdu (http://www.hifi-remote.com/forums/dload.php?action=file&file_id=25809)

#include "PinDefinitionsAndMore.h"
#include <Arduino.h>
#include <IRremote.h>
#include <SoftwareSerial.h>

#define IR_CODE_NUM_BITS 32
#define DEBUG true

const int powerPin = 12;
const int potentiometerPin = A5;
const int volOvPin = 11;
const int redLedPin = 13;
const int opticalPin = 10;
const int bluetoothPin = 9;
const int scrollPin = 6;
const int blueLedPin = 5;
const int joystickRxPin = A0;
const int joystickRyPin = A1;
const int joystickButtonPin = 2;
//https://www.espressif.com/sites/default/files/documentation/4b-esp8266_at_command_examples_en.pdf
const unsigned long keepAliveTimeout = 4999;

IRsend irsend;
int powerPinState = 0;
int volumeValue = 0;
int volumeLevel = 1;
int volumeTracker = 1;
int volOvPinState = 0;
int opticalPinState = 0;
int bluetoothPinState = 0;
int scrollPinState = 0;

SoftwareSerial esp8266(8, 7);
String output = "";
String tcpDataInOutput = "";
String tcpDataInSendLength = "";
String joystickOutput = "";
String joystickSendLength = "";
String keepAliveOutput = "";
String keepAliveSendLength = "";
String dataOutResult = "";
String dataInResponse = "";
String dataOutResponse = "";
int xPosition = 0;
int yPosition = 0;
int joystickPinState = 0;
int mapX = 0;
int mapY = 0;
bool volumeFirstRead = true;
bool clientConnected = false;
bool esp8266Init = false;
unsigned long timeValue = 0;

void setup() {
  Serial.begin(9600);
  esp8266.begin(9600);
  if (DEBUG) {
    Serial.println("Serial ready");
  }

  pinMode(powerPin, INPUT_PULLUP);
  pinMode(volOvPin, INPUT_PULLUP);
  pinMode(opticalPin, INPUT_PULLUP);
  pinMode(bluetoothPin, INPUT_PULLUP);
  pinMode(scrollPin, INPUT_PULLUP);
  pinMode(redLedPin, OUTPUT);
  pinMode(blueLedPin, OUTPUT);
  pinMode(joystickRxPin, INPUT);
  pinMode(joystickRyPin, INPUT);
  pinMode(joystickButtonPin, INPUT_PULLUP);

  IrSender.begin(IR_SEND_PIN, ENABLE_LED_FEEDBACK); // To-do: change to redLed pin?
  digitalWrite(redLedPin, HIGH);
  if (DEBUG) {
    Serial.println("Infared ready");
  }
}

void loop() {
  timeValue = millis();
  while ((timeValue + keepAliveTimeout) > millis()) {
    InnerLoop();
  }
  if (clientConnected) {
    keepAliveOutput = "ka\r\n";
    keepAliveSendLength = "AT+CIPSEND=0," + String(keepAliveOutput.length()) + "\r\n";
    TcpDataOut(keepAliveSendLength, 100);
    TcpDataOut(keepAliveOutput, 100);
    if (DEBUG) {
      Serial.print("Send keep alive. ");
      Serial.println("timeValue: " + String(timeValue) + " + keepAliveTimeout: " + String(timeValue + keepAliveTimeout));
    }
  } else {
    if (DEBUG) {
      Serial.print("Keep alive no client. ");
      Serial.println("timeValue: " + String(timeValue) + " + keepAliveTimeout: " + String(timeValue + keepAliveTimeout));
    }
  }
}

void InnerLoop() {
  //Serial.println("inner loop");

  powerPinState = digitalRead(powerPin);
  if (powerPinState == LOW) {
    if (DEBUG) {
      Serial.println("Power on sound bar");
    }
    digitalWrite(redLedPin, LOW);
    irsend.sendNEC(0x807F08F7U, IR_CODE_NUM_BITS);
    delay(250);
  }

  volumeValue = analogRead(potentiometerPin);
  volumeLevel = volumeValue / 64;

  if (volumeFirstRead) {
    volumeTracker = volumeLevel;
    volumeFirstRead = false;
  }

  if (volumeLevel != volumeTracker) {
    if (volumeLevel < volumeTracker) {
      if (DEBUG) {
        Serial.print("Volume down: ");
        Serial.print(volumeValue);
        Serial.print("  ");
        Serial.println(volumeLevel);
      }
      digitalWrite(redLedPin, LOW);
      irsend.sendNEC(0x807F10EFU, IR_CODE_NUM_BITS);
      volumeTracker = volumeLevel;
    } else {
      if (DEBUG) {
        Serial.print("Volume up: ");
        Serial.print(volumeValue);
        Serial.print("  ");
        Serial.println(volumeLevel);
      }
      digitalWrite(redLedPin, LOW);
      irsend.sendNEC(0x807F8877U, IR_CODE_NUM_BITS);
      volumeTracker = volumeLevel;
    }
    delay(250);
  }

  volOvPinState = digitalRead(volOvPin);
  if (volOvPinState == LOW) {
    if (volumeLevel < 7) {
      if (DEBUG) {
        Serial.println("Volume down (override)");
      }
      digitalWrite(redLedPin, LOW);
      irsend.sendNEC(0x807F10EFU, IR_CODE_NUM_BITS);
    } else {
      if (DEBUG) {
        Serial.println("Volume up (override)");
      }
      digitalWrite(redLedPin, LOW);
      irsend.sendNEC(0x807F8877U, IR_CODE_NUM_BITS);
    }
    delay(250);
  }

  opticalPinState = digitalRead(opticalPin);
  if (opticalPinState == LOW) {
    if (DEBUG) {
      Serial.println("Optical");
    }
    digitalWrite(redLedPin, LOW);
    irsend.sendNEC(0x807F926DU, IR_CODE_NUM_BITS);
    delay(250);
  }

  bluetoothPinState = digitalRead(bluetoothPin);
  if (bluetoothPinState == LOW) {
    if (DEBUG) {
      Serial.println("Bluetooth");
    }
    digitalWrite(redLedPin, LOW);
    irsend.sendNEC(0x807F52ADU, IR_CODE_NUM_BITS);
    delay(250);
  }

  xPosition = analogRead(joystickRxPin);
  yPosition = analogRead(joystickRyPin);
  joystickPinState = digitalRead(joystickButtonPin);
  mapX = map(xPosition, 0, 1023, -512, 512);
  mapY = map(yPosition, 0, 1023, -512, 512);
  scrollPinState = digitalRead(scrollPin);

  //joystickOutput = String(mapX) + "," + String(mapY) + "," + String(xPosition) + "," + String(yPosition) + "\r\n";
  //Serial.print(joystickOutput);
  //delay(500);

  if ((joystickPinState == 0 || scrollPinState == 0 || mapX > 25 || mapX < -25 || mapY > 25 || mapY < -25) && clientConnected) {
    joystickOutput = String(mapX) + "," + String(mapY) + "," + String(joystickPinState) + "," + String(scrollPinState) + "\r\n";
    joystickSendLength = "AT+CIPSEND=0," + String(joystickOutput.length()) + "\r\n";
    TcpDataOut(joystickSendLength, 100);
    TcpDataOut(joystickOutput, 100);
    if (DEBUG) {
      Serial.print(joystickOutput);
    }
    digitalWrite(blueLedPin, LOW);
  }

  if (scrollPinState == 0 && !esp8266Init) {
    if (DEBUG) {
      Serial.println("Starting esp8266...");
    }
    InitializeEsp8266();
    esp8266Init = true;
    if (DEBUG) {
      Serial.println("Esp8266 ready");
    }
  }

  if (esp8266Init) {
    TcpDataIn(200);
  }
  digitalWrite(redLedPin, HIGH);
  if (clientConnected) {
    digitalWrite(blueLedPin, HIGH);
  }
}

void InitializeEsp8266() {
  TcpDataOut("AT+RST\r\n", 3000); //reset module
  TcpDataOut("AT+CWMODE=1\r\n", 1000);
  TcpDataOut("AT+CWJAP=\"***REMOVED***\",\"***REMOVED***\"\r\n", 2000);
  while (!esp8266.find("OK")) {
  }
  dataOutResult = TcpDataOut("AT+CIFSR\r\n", 1000);
  if (dataOutResult.indexOf("0.0") > 0) {
    if (DEBUG) {
      Serial.println("INVALID IP!!!");
    }
    ResetEsp8266();
  }
  TcpDataOut("AT+CIPMUX=1\r\n", 1000); //enable multiple connections
  TcpDataOut("AT+CIPSERVER=1,3000\r\n", 2000);
}

void ResetEsp8266() {
  BlinkEsp8266Led();
  if (DEBUG) {
    Serial.println("Restarting esp8266...");
  }
  InitializeEsp8266();
  if (DEBUG) {
    Serial.println("Esp8266 ready");
  }
  clientConnected = false;
}

void BlinkEsp8266Led() {
  digitalWrite(blueLedPin, LOW);
  delay(100);
  digitalWrite(blueLedPin, HIGH);
  delay(100);
  digitalWrite(blueLedPin, LOW);
  delay(100);
  digitalWrite(blueLedPin, HIGH);
  delay(100);
  digitalWrite(blueLedPin, LOW);
  delay(100);
  digitalWrite(blueLedPin, HIGH);
  delay(100);
  digitalWrite(blueLedPin, LOW);
  delay(100);
  digitalWrite(blueLedPin, HIGH);
  delay(100);
  digitalWrite(blueLedPin, LOW);
}

void TcpDataIn(const int timeout) {
  dataInResponse = "";
  long int time = millis();
  while ((time + timeout) > millis()) {
    while (esp8266.available()) {
      char c = esp8266.read();
      dataInResponse += c;
    }
  }
  if (dataInResponse.length() == 0) {
    if (!clientConnected) {
      digitalWrite(blueLedPin, HIGH);
      delay(100);
      digitalWrite(blueLedPin, LOW);
      delay(100);
    }
    return;
  }
  if (DEBUG) {
    Serial.println("received: " + dataInResponse);
  }
  
  if (dataInResponse.indexOf("zzzz") > 0 || dataInResponse.indexOf("zzz") > 0 || dataInResponse.indexOf("zz") > 0) {
    clientConnected = true;
    if (DEBUG) {
      Serial.println("Client connected");
    }
    tcpDataInOutput = "initack\r\n";
    tcpDataInSendLength = "AT+CIPSEND=0," + String(tcpDataInOutput.length()) + "\r\n";
    TcpDataOut(tcpDataInSendLength, 100);
    TcpDataOut(tcpDataInOutput, 100);
    clientConnected = true;
    return;
  }
  
  if (dataInResponse.indexOf("nlink") > 0) {
    if (DEBUG) {
      Serial.println("Unlink detected");
    }
    clientConnected = false;
    return;
  }

  tcpDataInOutput = "ok\r\n";
  tcpDataInSendLength = "AT+CIPSEND=0," + String(tcpDataInOutput.length()) + "\r\n";
  TcpDataOut(tcpDataInSendLength, 100);
  TcpDataOut(tcpDataInOutput, 100);
}

String TcpDataOut(String command, const int timeout) {
  dataOutResponse = "";
  esp8266.print(command);
  long int time = millis();
  while ((time + timeout) > millis()) {
    while (esp8266.available()) {
      char c = esp8266.read();
      dataOutResponse += c;
    }
  }

  if (dataOutResponse.indexOf("link is not") > 0) {
    if (DEBUG) {
      Serial.println("Client disconnect tcp data out");
    }
    clientConnected = false;
    return;
  }

  if (dataOutResponse.indexOf("Error") > 0) {
    if (DEBUG) {
      Serial.println("Error in TcpDataOut");
    }
    ResetEsp8266();
  }
  if (DEBUG) {
    Serial.println(dataOutResponse);
  }
  return dataOutResponse;
}

/*
  Serial.println(F("Enter number of signal to send (1 .. 20)"));
  long commandno = Serial.parseInt();
  joystickButtonPinitch (commandno) {
  case 1L:
    irsend.sendNEC(0x807F08F7U, IR_CODE_NUM_BITS);
    break;
  case 2L:
    irsend.sendNEC(0x807FE817U, IR_CODE_NUM_BITS);
    break;
  case 3L:
    irsend.sendNEC(0x807F52ADU, IR_CODE_NUM_BITS);
    break;
  case 4L:
    irsend.sendNEC(0x807F926DU, IR_CODE_NUM_BITS);
    break;
  case 5L:
    irsend.sendNEC(0x807FE21DU, IR_CODE_NUM_BITS);
    break;
  case 6L:
    irsend.sendNEC(0x807F50AFU, IR_CODE_NUM_BITS);
    break;
  case 7L:
    irsend.sendNEC(0x807F8877U, IR_CODE_NUM_BITS);
    break;
  case 8L:
    irsend.sendNEC(0x807F28D7U, IR_CODE_NUM_BITS);
    break;
  case 9L:
    irsend.sendNEC(0x807F10EFU, IR_CODE_NUM_BITS);
    break;
  case 10L:
    irsend.sendNEC(0x807F906FU, IR_CODE_NUM_BITS);
    break;
  case 11L:
    irsend.sendNEC(0x807F7A85U, IR_CODE_NUM_BITS);
    break;
  case 12L:
    irsend.sendNEC(0x807FC23DU, IR_CODE_NUM_BITS);
    break;
  case 13L:
    irsend.sendNEC(0x807F02FDU, IR_CODE_NUM_BITS);
    break;
  case 14L:
    irsend.sendNEC(0x807FC837U, IR_CODE_NUM_BITS);
    break;
  case 15L:
    irsend.sendNEC(0x807FB24DU, IR_CODE_NUM_BITS);
    break;
  case 16L:
    irsend.sendNEC(0x807F32CDU, IR_CODE_NUM_BITS);
    break;
  case 17L:
    irsend.sendNEC(0x807FD22DU, IR_CODE_NUM_BITS);
    break;
  case 18L:
    irsend.sendNEC(0x807F0AF5U, IR_CODE_NUM_BITS);
    break;
  case 19L:
    irsend.sendNEC(0x807FF20DU, IR_CODE_NUM_BITS);
    break;
  case 20L:
    irsend.sendNEC(0x807F728DU, IR_CODE_NUM_BITS);
    break;
  case 21L:
    irsend.sendSAMSUNG(POWER, IR_CODE_NUM_BITS);
    break;
  case 22L:
    irsend.sendSAMSUNG(VOLUME_UP, IR_CODE_NUM_BITS);
    break;
  case 23L:
    irsend.sendSAMSUNG(VOLUME_DOWN, IR_CODE_NUM_BITS);
    break;
  default:
    Serial.println(F("Invalid number entered, try again"));
    break;
  }

  #define POWER 0xE0E040BF
  #define VOLUME_UP 0xE0E0E01F
  #define VOLUME_DOWN 0xE0E0D02F

*/

// Command #1: Power
// Protocol: nec1, Parameters: hex=247U D=1U param3=0U param4=0U F=16U

// Command #2: Mute
// Protocol: nec1, Parameters: hex=23U D=1U param3=0U param4=0U F=23U

// Command #3: BT
// Protocol: nec1, Parameters: hex=173U D=1U param3=0U param4=0U F=74U

// Command #4: Optical
// Protocol: nec1, Parameters: hex=109U D=1U param3=0U param4=0U F=73U

// Command #5: Line In
// Protocol: nec1, Parameters: hex=29U D=1U param3=0U param4=0U F=71U

// Command #6: USB
// Protocol: nec1, Parameters: hex=175U D=1U param3=0U param4=0U F=10U

// Command #7: up arrow
// Protocol: nec1, Parameters: hex=119U D=1U param3=0U param4=0U F=17U

// Command #8: right arrow
// Protocol: nec1, Parameters: hex=215U D=1U param3=0U param4=0U F=20U

// Command #9: down arrow
// Protocol: nec1, Parameters: hex=239U D=1U param3=0U param4=0U F=8U

// Command #10: left arrow
// Protocol: nec1, Parameters: hex=111U D=1U param3=0U param4=0U F=9U

// Command #11: Select
// Protocol: nec1, Parameters: hex=133U D=1U param3=0U param4=0U F=94U

// Command #12: General
// Protocol: nec1, Parameters: hex=61U D=1U param3=0U param4=0U F=67U

// Command #13: Voice
// Protocol: nec1, Parameters: hex=253U D=1U param3=0U param4=0U F=64U

// Command #14: Reset
// Protocol: nec1, Parameters: hex=55U D=1U param3=0U param4=0U F=19U

// Command #15: Bass
// Protocol: nec1, Parameters: hex=77U D=1U param3=0U param4=0U F=77U

// Command #16: Bass+
// Protocol: nec1, Parameters: hex=205U D=1U param3=0U param4=0U F=76U

// Command #17: Bass-
// Protocol: nec1, Parameters: hex=45U D=1U param3=0U param4=0U F=75U

// Command #18: Treble
// Protocol: nec1, Parameters: hex=245U D=1U param3=0U param4=0U F=80U

// Command #19: Treble+
// Protocol: nec1, Parameters: hex=13U D=1U param3=0U param4=0U F=79U

// Command #20: Treble-
// Protocol: nec1, Parameters: hex=141U D=1U param3=0U param4=0U F=78U