//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalVideoPlayer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LocalVideoPlayer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon blue_link {
            get {
                object obj = ResourceManager.GetObject("blue_link", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap close {
            get {
                object obj = ResourceManager.GetObject("close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap downarrow {
            get {
                object obj = ResourceManager.GetObject("downarrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap extras {
            get {
                object obj = ResourceManager.GetObject("extras", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppStarting=C:\Windows\cursors\aero_working_xl.ani
        ///Arrow=C:\Windows\cursors\aero_arrow_xl.cur
        ///Hand=C:\Windows\cursors\aero_link_xl.cur
        ///Help=C:\Windows\cursors\aero_helpsel_xl.cur
        ///No=C:\Windows\cursors\aero_unavail_xl.cur
        ///NWPen=C:\Windows\cursors\aero_pen_xl.cur
        ///SizeAll=C:\Windows\cursors\aero_move_xl.cur
        ///SizeNESW=C:\Windows\cursors\aero_nesw_xl.cur
        ///SizeNS=C:\Windows\cursors\aero_ns_xl.cur
        ///SizeNWSE=C:\Windows\cursors\aero_nwse_xl.cur
        ///SizeWE=C:\Windows\cursors\aero_ew_xl.cur
        ///UpArrow=C:\Windows\curs [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string keys_aero_xl {
            get {
                return ResourceManager.GetString("keys_aero_xl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppStarting=C:\Windows\cursors\aero_working.ani
        ///Arrow=C:\Windows\cursors\aero_arrow.cur
        ///Hand=C:\Windows\cursors\aero_link.cur
        ///Help=C:\Windows\cursors\aero_helpsel.cur
        ///No=C:\Windows\cursors\aero_unavail.cur
        ///NWPen=C:\Windows\cursors\aero_pen.cur
        ///SizeAll=C:\Windows\cursors\aero_move.cur
        ///SizeNESW=C:\Windows\cursors\aero_nesw.cur
        ///SizeNS=C:\Windows\cursors\aero_ns.cur
        ///SizeNWSE=C:\Windows\cursors\aero_nwse.cur
        ///SizeWE=C:\Windows\cursors\aero_ew.cur
        ///UpArrow=C:\Windows\cursors\aero_up.cur
        ///Wait=C:\Windows\ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string keys_backup {
            get {
                return ResourceManager.GetString("keys_backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppStarting=\Resources\blue_cursors_xl\blue_working_xl_clean.ani
        ///Arrow=\Resources\blue_cursors_xl\blue_arrow_xl.cur
        ///Hand=\Resources\blue_cursors_xl\blue_link_xl.cur
        ///Help=\Resources\blue_cursors_xl\blue_helpsel_xl.cur
        ///No=\Resources\blue_cursors_xl\blue_unavail_xl.cur
        ///NWPen=\Resources\blue_cursors_xl\blue_pen_xl.cur
        ///SizeAll=\Resources\blue_cursors_xl\blue_move_xl.cur
        ///SizeNESW=\Resources\blue_cursors_xl\blue_nesw_xl.cur
        ///SizeNS=\Resources\blue_cursors_xl\blue_ns_xl.cur
        ///SizeNWSE=\Resources\blue_cursors_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string keys_custom {
            get {
                return ResourceManager.GetString("keys_custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap noprev {
            get {
                object obj = ResourceManager.GetObject("noprev", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap noprevSeason {
            get {
                object obj = ResourceManager.GetObject("noprevSeason", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pause {
            get {
                object obj = ResourceManager.GetObject("pause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pause64 {
            get {
                object obj = ResourceManager.GetObject("pause64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap play {
            get {
                object obj = ResourceManager.GetObject("play", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap play64 {
            get {
                object obj = ResourceManager.GetObject("play64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap smallPlay {
            get {
                object obj = ResourceManager.GetObject("smallPlay", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ThumbBottom {
            get {
                object obj = ResourceManager.GetObject("ThumbBottom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ThumbMiddle {
            get {
                object obj = ResourceManager.GetObject("ThumbMiddle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ThumbSpanBottom {
            get {
                object obj = ResourceManager.GetObject("ThumbSpanBottom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ThumbSpanTop {
            get {
                object obj = ResourceManager.GetObject("ThumbSpanTop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ThumbTop {
            get {
                object obj = ResourceManager.GetObject("ThumbTop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap uparrow {
            get {
                object obj = ResourceManager.GetObject("uparrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
